name: webview_app
description: Flutter WebView APK with Lottie Splash and App Icon

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.7.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/splash.json
    - assets/logo.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
